-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("ALT + CTRL + R")
hl.bind("ALT + CTRL + R", hl.dsp.exec_cmd("dms ipc screenRecorder toggleRecording"), { description = "dms ipc screenRecorderLH togglePortal" })
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.layout("colresize +conf"), { description = "cycle width" })
hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.window.center(), { description = "Center Window" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("dolphin"), { description = "Open File manager" })
hl.unbind("SUPER + BracketLeft")
hl.bind("SUPER + BracketLeft", hl.dsp.layout("consume_or_expel prev"), { description = "Consume Prev" })
hl.unbind("SUPER + SHIFT + Escape")
hl.unbind("SUPER + bracketright")
hl.bind("SUPER + bracketright", hl.dsp.layout("consume_or_expel next"), { description = "Consume next" })
