-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "nier-cursors-bin")
hl.env("XCURSOR_THEME", "nier-cursors-bin")
hl.env("HYPRCURSOR_SIZE", "28")
hl.env("XCURSOR_SIZE", "28")
