-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-1", mode = "2560x1600@240.000", position = "0x240", scale = 1.33203125, vrr = 0, bitdepth = 10 })
hl.monitor({ output = "HDMI-A-1", mode = "3440x1440@239.999", position = "1920x0", scale = 1, vrr = 0, bitdepth = 10, sdrsaturation = 1.1 })
