-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "HDMI-A-1", mode = "3440x1440@239.999", position = "1598x0", scale = 1, vrr = 2, bitdepth = 10, sdrbrightness = 1.2 })
hl.monitor({ output = "eDP-1", mode = "2560x1600@240.000", position = "0x0", scale = 1.6015625, vrr = 0, bitdepth = 10 })
